"""Centralized feature metadata registry documenting all Phase 7.5 ML features."""

from typing import List
from app.ml.schemas.feature_schema import FeatureMetadataItem


FEATURE_REGISTRY: List[FeatureMetadataItem] = [
    # 1. Base & Identification Features
    FeatureMetadataItem(
        name="content_id",
        type="numeric",
        category="identification",
        description="Unique identifier of the content asset",
        source="analytics-contract-v1.content_id",
        formula="content_id",
        nullable=False,
        allowed_range=">= 1",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="category_id",
        type="categorical",
        category="identification",
        description="Primary catalog category ID (nullable/unassigned)",
        source="analytics-contract-v1.category_id",
        formula="category_id",
        nullable=True,
        allowed_range=">= 1 or null",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="language_id",
        type="categorical",
        category="identification",
        description="Content language ID (nullable/unassigned)",
        source="analytics-contract-v1.language_id",
        formula="language_id",
        nullable=True,
        allowed_range=">= 1 or null",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="platform",
        type="categorical",
        category="platform",
        description="Client device playback platform",
        source="analytics-contract-v1.platform",
        formula="platform.upper()",
        nullable=False,
        allowed_range="IOS, ANDROID, WEB",
        future_leakage_risk=False,
    ),
    # 2. Raw Volume Features
    FeatureMetadataItem(
        name="sessions",
        type="numeric",
        category="volume",
        description="Total playback session initiations",
        source="analytics-contract-v1.sessions",
        formula="sessions",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="plays",
        type="numeric",
        category="volume",
        description="Total playback play events",
        source="analytics-contract-v1.plays",
        formula="plays",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="unique_viewers",
        type="numeric",
        category="volume",
        description="Count of distinct viewers",
        source="analytics-contract-v1.unique_viewers",
        formula="unique_viewers",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_seconds",
        type="numeric",
        category="volume",
        description="Cumulative watch duration in seconds",
        source="analytics-contract-v1.watch_time_seconds",
        formula="watch_time_seconds",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="completed_plays",
        type="numeric",
        category="volume",
        description="Total completed playback sessions",
        source="analytics-contract-v1.completed_plays",
        formula="completed_plays",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="buffering_events",
        type="numeric",
        category="volume",
        description="Total player buffering stall events",
        source="analytics-contract-v1.buffering_events",
        formula="buffering_events",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="playback_errors",
        type="numeric",
        category="volume",
        description="Total fatal or non-fatal player errors",
        source="analytics-contract-v1.playback_errors",
        formula="playback_errors",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="quality_changes",
        type="numeric",
        category="volume",
        description="Total adaptive bitrate rendition switches",
        source="analytics-contract-v1.quality_changes",
        formula="quality_changes",
        nullable=False,
        allowed_range=">= 0",
        future_leakage_risk=False,
    ),
    # 3. Derived Engagement & Reliability Features
    FeatureMetadataItem(
        name="plays_per_session",
        type="numeric",
        category="engagement",
        description="Ratio of plays per session",
        source="derived",
        formula="plays / sessions (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="plays_per_viewer",
        type="numeric",
        category="engagement",
        description="Average plays initiated per unique viewer",
        source="derived",
        formula="plays / unique_viewers (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_per_play",
        type="numeric",
        category="engagement",
        description="Average watch duration per play in seconds",
        source="derived",
        formula="watch_time_seconds / plays (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_per_session",
        type="numeric",
        category="engagement",
        description="Average watch duration per session in seconds",
        source="derived",
        formula="watch_time_seconds / sessions (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="completion_rate",
        type="numeric",
        category="engagement",
        description="Ratio of completed plays to total plays",
        source="derived",
        formula="completed_plays / plays (or 0.0)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="completed_plays_ratio",
        type="numeric",
        category="engagement",
        description="Ratio of completed plays to total sessions",
        source="derived",
        formula="completed_plays / sessions (or 0.0)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="buffering_rate",
        type="numeric",
        category="engagement",
        description="Buffering stalls per playback attempt",
        source="derived",
        formula="buffering_events / plays (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="error_rate",
        type="numeric",
        category="engagement",
        description="Playback errors per playback attempt",
        source="derived",
        formula="playback_errors / plays (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="quality_change_rate",
        type="numeric",
        category="engagement",
        description="Quality switches per playback attempt",
        source="derived",
        formula="quality_changes / plays (or 0.0)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    # 4. Temporal Features (UTC Semantics)
    FeatureMetadataItem(
        name="day_of_week",
        type="numeric",
        category="temporal",
        description="ISO day of week in UTC (0=Monday, 6=Sunday)",
        source="date",
        formula="date.dt.dayofweek",
        nullable=False,
        allowed_range="0 to 6",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="day_of_month",
        type="numeric",
        category="temporal",
        description="Day of month in UTC (1 to 31)",
        source="date",
        formula="date.dt.day",
        nullable=False,
        allowed_range="1 to 31",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="day_of_year",
        type="numeric",
        category="temporal",
        description="Day of year in UTC (1 to 366)",
        source="date",
        formula="date.dt.dayofyear",
        nullable=False,
        allowed_range="1 to 366",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="week_of_year",
        type="numeric",
        category="temporal",
        description="ISO week number of year in UTC (1 to 53)",
        source="date",
        formula="date.dt.isocalendar().week",
        nullable=False,
        allowed_range="1 to 53",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="month",
        type="numeric",
        category="temporal",
        description="Month of year in UTC (1 to 12)",
        source="date",
        formula="date.dt.month",
        nullable=False,
        allowed_range="1 to 12",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="quarter",
        type="numeric",
        category="temporal",
        description="Calendar quarter in UTC (1 to 4)",
        source="date",
        formula="date.dt.quarter",
        nullable=False,
        allowed_range="1 to 4",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="is_weekend",
        type="numeric",
        category="temporal",
        description="Binary indicator: 1 if Saturday/Sunday else 0",
        source="date",
        formula="1 if day_of_week in [5, 6] else 0",
        nullable=False,
        allowed_range="0 or 1",
        future_leakage_risk=False,
    ),
    # 5. Content Performance Shares
    FeatureMetadataItem(
        name="content_play_share",
        type="numeric",
        category="content",
        description="Content share of daily total plays across dataset",
        source="derived",
        formula="plays / sum(plays_for_date)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="content_watch_time_share",
        type="numeric",
        category="content",
        description="Content share of daily total watch time across dataset",
        source="derived",
        formula="watch_time_seconds / sum(watch_time_for_date)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="content_viewer_share",
        type="numeric",
        category="content",
        description="Content share of daily total viewers across dataset",
        source="derived",
        formula="unique_viewers / sum(viewers_for_date)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    # 6. Historical Lag Features (1-Day Prior on content_id + platform)
    FeatureMetadataItem(
        name="plays_lag_1d",
        type="numeric",
        category="lag",
        description="Plays for this content and platform on the prior day",
        source="derived",
        formula="shift(1) partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_lag_1d",
        type="numeric",
        category="lag",
        description="Watch time for this content and platform on the prior day",
        source="derived",
        formula="shift(1) partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="viewers_lag_1d",
        type="numeric",
        category="lag",
        description="Unique viewers for this content and platform on the prior day",
        source="derived",
        formula="shift(1) partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="completion_rate_lag_1d",
        type="numeric",
        category="lag",
        description="Completion rate for this content and platform on the prior day",
        source="derived",
        formula="shift(1) partitioned by (content_id, platform)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    # 7. Historical Rolling Features (7-Day Window on content_id + platform)
    FeatureMetadataItem(
        name="plays_rolling_7d",
        type="numeric",
        category="rolling",
        description="7-day historical rolling sum of plays (inclusive of current day)",
        source="derived",
        formula="rolling(7).sum() partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_rolling_7d",
        type="numeric",
        category="rolling",
        description="7-day historical rolling sum of watch time (inclusive of current day)",
        source="derived",
        formula="rolling(7).sum() partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="viewers_rolling_7d",
        type="numeric",
        category="rolling",
        description="7-day historical rolling sum of viewers (inclusive of current day)",
        source="derived",
        formula="rolling(7).sum() partitioned by (content_id, platform)",
        nullable=False,
        allowed_range=">= 0.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="completion_rate_rolling_7d",
        type="numeric",
        category="rolling",
        description="7-day historical rolling completion rate (completed_plays_7d / plays_7d)",
        source="derived",
        formula="completed_plays_rolling_7d / plays_rolling_7d (or 0.0)",
        nullable=False,
        allowed_range="[0.0, 1.0]",
        future_leakage_risk=False,
    ),
    # 8. Growth Features (1D and 7D Ratios)
    FeatureMetadataItem(
        name="plays_growth_1d",
        type="numeric",
        category="growth",
        description="Day-over-day plays growth ratio (0.25 = +25%)",
        source="derived",
        formula="(plays - plays_lag_1d) / plays_lag_1d",
        nullable=False,
        allowed_range=">= -1.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="watch_time_growth_1d",
        type="numeric",
        category="growth",
        description="Day-over-day watch time growth ratio",
        source="derived",
        formula="(watch_time - watch_time_lag_1d) / watch_time_lag_1d",
        nullable=False,
        allowed_range=">= -1.0",
        future_leakage_risk=False,
    ),
    FeatureMetadataItem(
        name="viewer_growth_1d",
        type="numeric",
        category="growth",
        description="Day-over-day viewer growth ratio",
        source="derived",
        formula="(viewers - viewers_lag_1d) / viewers_lag_1d",
        nullable=False,
        allowed_range=">= -1.0",
        future_leakage_risk=False,
    ),
]


def get_feature_registry() -> List[FeatureMetadataItem]:
    """Return the static list of all registered engineered feature specifications."""
    return FEATURE_REGISTRY.copy()


NUMERIC_FEATURES: List[str] = [item.name for item in FEATURE_REGISTRY if item.type == "numeric"]
CATEGORICAL_FEATURES: List[str] = [item.name for item in FEATURE_REGISTRY if item.type == "categorical"]

